import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 24,
    height: '100%',
    width: '100%',
  },
  title: {
    marginTop: 50,
    paddingVertical: 8,
    width: '80%',
    textAlign: 'left',
    fontFamily: 'recoleta-regular',
    fontSize: 40,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  resourceTitle: {
    textAlign: 'left',
    fontSize: 24,
    margin: 24,
    fontFamily: 'cabinet-grotesk-regular',
    color: 'white',
  },
  resourceBody: {
    textAlign: 'left',
    fontSize: 14,
    margin: 24,
    fontFamily: 'cabinet-grotesk-regular',
    color: 'white',
  },
  orangeCard: {
    display: 'flex',
    justifyContent: 'center',
    width: '80%',
    height: 169,
    borderRadius: 8,
    marginVertical: 8,
    backgroundColor: '#ED713E',
  },
  yellowCard: {
    display: 'flex',
    justifyContent: 'center',
    width: '80%',
    height: 169,
    borderRadius: 8,
    marginVertical: 8,
    backgroundColor: 'rgba(254, 159, 51, 1)',
  },
  greenCard: {
    display: 'flex',
    justifyContent: 'center',
    width: '80%',
    height: 169,
    borderRadius: 8,
    marginVertical: 8,
    backgroundColor: '#8DADA5',
  },
  blueCard: {
    display: 'flex',
    justifyContent: 'center',
    width: '80%',
    height: 169,
    borderRadius: 8,
    marginVertical: 8,
    backgroundColor: '#91A8D1',
  },
  redButton: {
    borderRadius: 8,
    width: 120,
    marginLeft: 24,
    flexDirection: 'row',
    backgroundColor: 'rgba(189, 43, 43, 1)',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  yellowButton: {
    borderRadius: 8,
    width: 178,
    marginLeft: 24,
    flexDirection: 'row',
    backgroundColor: '#ED713E',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  greenButton: {
    borderRadius: 8,
    width: 187,
    marginLeft: 24,
    flexDirection: 'row',
    backgroundColor: '#438373',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  blueButton: {
    borderRadius: 8,
    width: 178,
    marginLeft: 24,
    flexDirection: 'row',
    backgroundColor: '#556A93',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  phoneIcon: {
    height: 16,
    width: 16,
    marginRight: 12,
  },
  flipIcon: {
    height: 16,
    width: 18,
    marginRight: 12,
  },
  buttonText: {
    fontFamily: 'cabinet-grotesk-bold',
    color: 'white',
  },
  front: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    height: '85%',
  },
  back: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    height: '85%',
  },
});
