const challengeData = [
  { title: 'Expressive Art', description: 'Expressive Art: Engage in a creative activity and get lost in the art of making something. Do not worry about how “good” it turns out! Read more here.' },
  { title: 'Short Exercise', description: 'Take a 30-minute walk outside.' },
  { title: 'Small Reads', description: 'Read a chapter of a book you have been meaning to start.' },
  { title: 'Eat Healthy', description: 'Cook a healthy meal from scratch.' },
  { title: 'Stay Connected', description: 'Call a friend or family member to catch up.' },
  { title: 'Journaling', description: 'Write in a journal for 15 minutes.' },
  { title: 'Clean Up', description: 'Spend an hour decluttering a part of your home.' },
  { title: 'Day 8', description: 'Try a new hobby or activity.' },
  { title: 'Day 9', description: 'Spend 30 minutes doing yoga or stretching.' },
  { title: 'Day 10', description: 'Watch a documentary or educational video.' },
  { title: 'Day 11', description: 'Create a list of goals for the next month.' },
  { title: 'Day 12', description: 'Write a letter to your future self.' },
  { title: 'Day 13', description: 'Spend time in nature and appreciate your surroundings.' },
  { title: 'Day 14', description: 'Try a new recipe or baking project.' },
  { title: 'Day 15', description: 'Plan a fun outing or activity for the weekend.' },
  { title: 'Day 16', description: 'Practice a random act of kindness.' },
  { title: 'Day 17', description: 'Learn a new skill or take an online course.' },
  { title: 'Day 18', description: 'Spend time organizing your digital files and photos.' },
  { title: 'Day 19', description: 'Do a workout or exercise routine.' },
  { title: 'Day 20', description: 'Spend an hour on a creative project or craft.' },
  { title: 'Day 21', description: 'Take a break from screens and enjoy some offline time.' },
  { title: 'Day 22', description: 'Create a vision board or mood board.' },
  { title: 'Day 23', description: 'Reflect on your accomplishments and set new intentions.' },
  { title: 'Day 24', description: 'Spend time volunteering or helping others.' },
  { title: 'Day 25', description: 'Watch a movie or read a book in a genre you usually do not explore.' },
  { title: 'Day 26', description: 'Do a digital detox for the day.' },
  { title: 'Day 27', description: 'Write a gratitude list of things you are thankful for.' },
  { title: 'Day 28', description: 'Try a new fitness class or activity.' },
  { title: 'Day 29', description: 'Spend time gardening or tending to plants.' },
  { title: 'Day 30', description: 'Reflect on the past 30 days and celebrate your progress.' },
];

export default challengeData;
